//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students
    {
        public int C_Identify { get; set; }
        public int StudentId { get; set; }
        public string StudentName { get; set; }
        public string Gender { get; set; }
        public System.DateTime Birthday { get; set; }
        public decimal StudentIdNo { get; set; }
        public string CardNo { get; set; }
        public string StuImage { get; set; }
        public int Age { get; set; }
        public string PhoneNumber { get; set; }
        public string StudentAddress { get; set; }
        public int ClassId { get; set; }
    
        public virtual StudentClass StudentClass { get; set; }
    }
}
